const DSASheet = require('../../models/sheets.model');
const connectDB = require('../seedConfig');

const loveBabbarData = {
  name: "Love Babbar DSA Sheet",
  slug: "love-babbar",
  description: "A comprehensive DSA sheet by Love Babbar covering 450+ problems.",
  topics: [
    {
      title: "Array",
      problems: [
        { title: "Reverse the array", link: "https://www.geeksforgeeks.org/write-a-program-to-reverse-an-array-or-string/", difficulty: "Easy", tags: ["array"] },
        { title: "Find the maximum and minimum element in an array", link: "https://www.geeksforgeeks.org/maximum-and-minimum-in-an-array/", difficulty: "Easy", tags: ["array"] },
        { title: "Find the Kth max and min element of an array", link: "https://practice.geeksforgeeks.org/problems/kth-smallest-element/0", difficulty: "Easy", tags: ["array", "sorting"] },
        { title: "Sort an array of 0s, 1s and 2s (Dutch National Flag)", link: "https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s/0", difficulty: "Easy", tags: ["array", "two-pointers"] },
        { title: "Move all the negative elements to one side of the array", link: "https://www.geeksforgeeks.org/move-negative-numbers-beginning-positive-end-constant-extra-space/", difficulty: "Easy", tags: ["array", "two-pointers"] },
        { title: "Find the Union and Intersection of two sorted arrays", link: "https://practice.geeksforgeeks.org/problems/union-of-two-arrays/0", difficulty: "Easy", tags: ["array", "sorting"] },
        { title: "Cyclically rotate an array by one", link: "https://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one/0", difficulty: "Easy", tags: ["array"] },
        { title: "Largest sum contiguous Subarray (Kadane's Algorithm)", link: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0", difficulty: "Easy", tags: ["array", "dp"] },
        { title: "Minimise the maximum difference between heights", link: "https://practice.geeksforgeeks.org/problems/minimize-the-heights3351/1", difficulty: "Medium", tags: ["array", "sorting", "greedy"] },
        { title: "Minimum number of Jumps to reach end of an array", link: "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0", difficulty: "Medium", tags: ["array", "greedy", "dp"] },
        { title: "Find duplicate in an array of N+1 Integers", link: "https://leetcode.com/problems/find-the-duplicate-number/", difficulty: "Medium", tags: ["array", "two-pointers", "binary-search"] },
        { title: "Merge 2 sorted arrays without using extra space", link: "https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays5135/1", difficulty: "Hard", tags: ["array", "sorting", "two-pointers"] },
        { title: "Kadane's Algorithm", link: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0", difficulty: "Easy", tags: ["array", "dp"] },
        { title: "Merge Intervals", link: "https://leetcode.com/problems/merge-intervals/", difficulty: "Medium", tags: ["array", "sorting"] },
        { title: "Next Permutation", link: "https://leetcode.com/problems/next-permutation/", difficulty: "Medium", tags: ["array", "two-pointers"] },
        { title: "Count Inversions", link: "https://practice.geeksforgeeks.org/problems/inversion-of-array/0", difficulty: "Medium", tags: ["array", "merge-sort"] },
        { title: "Best time to buy and sell stock", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", difficulty: "Easy", tags: ["array", "greedy"] },
        { title: "Find all pairs on integer array whose sum is equal to given number", link: "https://practice.geeksforgeeks.org/problems/count-pairs-with-given-sum5022/1", difficulty: "Easy", tags: ["array", "hashmap"] },
        { title: "Find common elements in 3 sorted arrays", link: "https://practice.geeksforgeeks.org/problems/common-elements1132/1", difficulty: "Easy", tags: ["array", "two-pointers"] },
        { title: "Rearrange the array in alternating positive and negative items with O(1) extra space", link: "https://www.geeksforgeeks.org/rearrange-array-alternating-positive-negative-items-o1-extra-space/", difficulty: "Medium", tags: ["array"] },
        { title: "Find if there is any subarray with sum equal to 0", link: "https://practice.geeksforgeeks.org/problems/subarray-with-0-sum/0", difficulty: "Easy", tags: ["array", "hashmap", "prefix-sum"] },
        { title: "Find factorial of a large number", link: "https://practice.geeksforgeeks.org/problems/factorials-of-large-numbers/0", difficulty: "Easy", tags: ["array", "math"] },
        { title: "Find maximum product subarray", link: "https://practice.geeksforgeeks.org/problems/maximum-product-subarray3604/1", difficulty: "Medium", tags: ["array", "dp"] },
        { title: "Find longest consecutive subsequence", link: "https://practice.geeksforgeeks.org/problems/longest-consecutive-subsequence/0", difficulty: "Medium", tags: ["array", "hashset"] },
        { title: "Find all elements that appear more than n/k times", link: "https://leetcode.com/problems/majority-element-ii/", difficulty: "Medium", tags: ["array", "hashmap", "voting-algorithm"] },
        { title: "Maximum profit by buying and selling a share at most twice", link: "https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-twice/", difficulty: "Hard", tags: ["array", "dp"] },
        { title: "Find whether an array is a subset of another array", link: "https://practice.geeksforgeeks.org/problems/array-subset-of-another-array/0", difficulty: "Easy", tags: ["array", "hashset"] },
        { title: "Find the triplet that sums to a given value", link: "https://practice.geeksforgeeks.org/problems/triplet-sum-in-array/0", difficulty: "Medium", tags: ["array", "two-pointers", "sorting"] },
        { title: "Trapping Rain Water", link: "https://practice.geeksforgeeks.org/problems/trapping-rain-water-1587115621/1", difficulty: "Hard", tags: ["array", "two-pointers", "stack"] },
        { title: "Chocolate Distribution Problem", link: "https://practice.geeksforgeeks.org/problems/chocolate-distribution-problem/0", difficulty: "Easy", tags: ["array", "sorting", "greedy"] },
        { title: "Smallest Subarray with sum greater than a given value", link: "https://practice.geeksforgeeks.org/problems/smallest-subarray-with-sum-greater-than-x/0", difficulty: "Medium", tags: ["array", "sliding-window"] },
        { title: "Three way partitioning of an array around a given value", link: "https://practice.geeksforgeeks.org/problems/three-way-partitioning/1", difficulty: "Easy", tags: ["array", "two-pointers"] },
        { title: "Minimum swaps required to bring elements less than or equal to K together", link: "https://practice.geeksforgeeks.org/problems/minimum-swaps-required-to-bring-all-elements-less-than-or-equal-to-k-together/0", difficulty: "Medium", tags: ["array", "sliding-window"] },
        { title: "Minimum number of operations required to make an array palindrome", link: "https://practice.geeksforgeeks.org/problems/palindromic-array/0", difficulty: "Easy", tags: ["array", "greedy", "two-pointers"] },
        { title: "Median of 2 sorted arrays of equal size", link: "https://practice.geeksforgeeks.org/problems/find-the-median0527/1", difficulty: "Hard", tags: ["array", "binary-search"] },
        { title: "Median of 2 sorted arrays of different size", link: "https://www.geeksforgeeks.org/median-of-two-sorted-arrays-of-different-sizes/", difficulty: "Hard", tags: ["array", "binary-search"] }
      ]
    },
    {
      title: "Matrix",
      problems: [
        { title: "Spiral traversal on a Matrix", link: "https://practice.geeksforgeeks.org/problems/spirally-traversing-a-matrix/0", difficulty: "Medium", tags: ["matrix", "simulation"] },
        { title: "Search an element in a matrix", link: "https://leetcode.com/problems/search-a-2d-matrix/", difficulty: "Medium", tags: ["matrix", "binary-search"] },
        { title: "Find median in a row wise sorted matrix", link: "https://practice.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix1527/1", difficulty: "Hard", tags: ["matrix", "binary-search"] },
        { title: "Find row with maximum number of 1s", link: "https://practice.geeksforgeeks.org/problems/row-with-max-1s0023/1", difficulty: "Easy", tags: ["matrix", "binary-search"] },
        { title: "Print elements in sorted order using row-column wise sorted matrix", link: "https://practice.geeksforgeeks.org/problems/sorted-matrix/0", difficulty: "Easy", tags: ["matrix", "heap"] },
        { title: "Maximum size rectangle in binary matrix", link: "https://practice.geeksforgeeks.org/problems/max-rectangle/1", difficulty: "Hard", tags: ["matrix", "stack", "dp"] },
        { title: "Find a specific pair in matrix", link: "https://www.geeksforgeeks.org/find-a-specific-pair-in-matrix/", difficulty: "Medium", tags: ["matrix", "dp"] },
        { title: "Rotate matrix by 90 degrees", link: "https://www.geeksforgeeks.org/rotate-a-matrix-by-90-degree-in-clockwise-direction-without-using-any-extra-space/", difficulty: "Medium", tags: ["matrix"] },
        { title: "Kth smallest element in a row-column wise sorted matrix", link: "https://practice.geeksforgeeks.org/problems/kth-element-in-matrix/1", difficulty: "Medium", tags: ["matrix", "binary-search", "heap"] },
        { title: "Common elements in all rows of a given matrix", link: "https://www.geeksforgeeks.org/common-elements-in-all-rows-of-a-given-matrix/", difficulty: "Medium", tags: ["matrix", "hashmap"] }
      ]
    },
    {
      title: "String",
      problems: [
        { title: "Reverse a String", link: "https://leetcode.com/problems/reverse-string/", difficulty: "Easy", tags: ["string", "two-pointers"] },
        { title: "Check whether a String is Palindrome or not", link: "https://practice.geeksforgeeks.org/problems/palindrome-string0817/1", difficulty: "Easy", tags: ["string", "two-pointers"] },
        { title: "Find Duplicate characters in a string", link: "https://www.geeksforgeeks.org/print-all-the-duplicates-in-the-input-string/", difficulty: "Easy", tags: ["string", "hashmap"] },
        { title: "Why strings are immutable in Java?", link: "https://www.baeldung.com/java-string-immutable", difficulty: "Easy", tags: ["string", "theory"] },
        { title: "Check whether one string is a rotation of another", link: "https://www.geeksforgeeks.org/a-program-to-check-if-strings-are-rotations-of-each-other/", difficulty: "Easy", tags: ["string"] },
        { title: "Check whether a string is a valid shuffle of two strings", link: "https://www.programiz.com/java-programming/examples/check-valid-shuffle-of-strings", difficulty: "Medium", tags: ["string", "recursion"] },
        { title: "Count and Say problem", link: "https://leetcode.com/problems/count-and-say/", difficulty: "Medium", tags: ["string", "simulation"] },
        { title: "Find Longest Palindromic Substring", link: "https://practice.geeksforgeeks.org/problems/longest-palindrome-in-a-string/0", difficulty: "Medium", tags: ["string", "dp", "two-pointers"] },
        { title: "Find Longest Recurring Subsequence in String", link: "https://practice.geeksforgeeks.org/problems/longest-repeating-subsequence/0", difficulty: "Medium", tags: ["string", "dp"] },
        { title: "Print all Subsequences of a string", link: "https://www.geeksforgeeks.org/print-subsequences-string/", difficulty: "Medium", tags: ["string", "recursion", "backtracking"] },
        { title: "Print all the permutations of the given string", link: "https://practice.geeksforgeeks.org/problems/permutations-of-a-given-string/0", difficulty: "Medium", tags: ["string", "recursion", "backtracking"] },
        { title: "Split the Binary string into two substrings with equal 0s and 1s", link: "https://www.geeksforgeeks.org/split-the-binary-string-into-substrings-with-equal-number-of-0s-and-1s/", difficulty: "Easy", tags: ["string"] },
        { title: "Word Wrap Problem", link: "https://practice.geeksforgeeks.org/problems/word-wrap/0", difficulty: "Hard", tags: ["string", "dp"] },
        { title: "Edit Distance", link: "https://practice.geeksforgeeks.org/problems/edit-distance3702/1", difficulty: "Hard", tags: ["string", "dp"] },
        { title: "Find next greater number with same set of digits", link: "https://practice.geeksforgeeks.org/problems/next-permutation/0", difficulty: "Medium", tags: ["string", "two-pointers"] },
        { title: "Balanced Parenthesis problem", link: "https://practice.geeksforgeeks.org/problems/parenthesis-checker/0", difficulty: "Easy", tags: ["string", "stack"] },
        { title: "Word Break Problem", link: "https://practice.geeksforgeeks.org/problems/word-break/0", difficulty: "Medium", tags: ["string", "dp", "trie"] },
        { title: "Rabin Karp Algorithm", link: "https://www.geeksforgeeks.org/rabin-karp-algorithm-for-pattern-searching/", difficulty: "Medium", tags: ["string", "hashing", "pattern-matching"] },
        { title: "KMP Algorithm (Longest Prefix Suffix)", link: "https://practice.geeksforgeeks.org/problems/longest-prefix-suffix2527/1", difficulty: "Hard", tags: ["string", "pattern-matching"] },
        { title: "Convert a Sentence into mobile numeric keypad sequence", link: "https://www.geeksforgeeks.org/convert-sentence-equivalent-mobile-numeric-keypad-sequence/", difficulty: "Easy", tags: ["string", "hashmap"] },
        { title: "Minimum number of bracket reversals needed to balance an expression", link: "https://practice.geeksforgeeks.org/problems/count-the-reversals/0", difficulty: "Hard", tags: ["string", "stack"] },
        { title: "Count All Palindromic Subsequences in a given String", link: "https://practice.geeksforgeeks.org/problems/count-palindromic-subsequences/1", difficulty: "Hard", tags: ["string", "dp"] },
        { title: "Count of number of given string in 2D character array", link: "https://www.geeksforgeeks.org/find-count-number-given-string-present-2d-character-array/", difficulty: "Medium", tags: ["string", "matrix", "dfs"] },
        { title: "Search a Word in a 2D Grid of characters", link: "https://practice.geeksforgeeks.org/problems/find-the-string-in-grid/0", difficulty: "Medium", tags: ["string", "matrix", "dfs"] },
        { title: "Boyer Moore Algorithm for Pattern Searching", link: "https://www.geeksforgeeks.org/boyer-moore-algorithm-for-pattern-searching/", difficulty: "Hard", tags: ["string", "pattern-matching"] },
        { title: "Converting Roman Numerals to Decimal", link: "https://practice.geeksforgeeks.org/problems/roman-number-to-integer/0", difficulty: "Easy", tags: ["string", "math"] },
        { title: "Longest Common Prefix", link: "https://leetcode.com/problems/longest-common-prefix/", difficulty: "Easy", tags: ["string", "trie"] },
        { title: "Number of flips to make binary string alternate", link: "https://practice.geeksforgeeks.org/problems/min-number-of-flips/0", difficulty: "Easy", tags: ["string", "greedy"] },
        { title: "Find the first repeated word in string", link: "https://practice.geeksforgeeks.org/problems/second-most-repeated-string-in-a-sequence/0", difficulty: "Easy", tags: ["string", "hashmap"] },
        { title: "Minimum number of swaps for bracket balancing", link: "https://practice.geeksforgeeks.org/problems/minimum-swaps-for-bracket-balancing/0", difficulty: "Medium", tags: ["string", "stack", "greedy"] },
        { title: "Find the longest common subsequence between two strings", link: "https://practice.geeksforgeeks.org/problems/longest-common-subsequence/0", difficulty: "Medium", tags: ["string", "dp"] },
        { title: "Program to generate all possible valid IP addresses from given string", link: "https://www.geeksforgeeks.org/program-generate-possible-valid-ip-addresses-given-string/", difficulty: "Medium", tags: ["string", "backtracking"] },
        { title: "Find the smallest window that contains all characters of string itself", link: "https://practice.geeksforgeeks.org/problems/smallest-distinct-window/0", difficulty: "Hard", tags: ["string", "sliding-window", "hashmap"] },
        { title: "Rearrange characters in a string such that no two adjacent are same", link: "https://practice.geeksforgeeks.org/problems/rearrange-characters/0", difficulty: "Medium", tags: ["string", "heap", "greedy"] },
        { title: "Minimum characters to be added at front to make string palindrome", link: "https://www.geeksforgeeks.org/minimum-characters-added-front-make-string-palindrome/", difficulty: "Hard", tags: ["string", "kmp"] },
        { title: "Given a sequence of words, print all anagrams together", link: "https://practice.geeksforgeeks.org/problems/k-anagrams-1/0", difficulty: "Medium", tags: ["string", "hashmap", "sorting"] },
        { title: "Find the smallest window in a string containing all characters of another string", link: "https://practice.geeksforgeeks.org/problems/smallest-window-in-a-string-containing-all-the-characters-of-another-string/0", difficulty: "Hard", tags: ["string", "sliding-window", "hashmap"] },
        { title: "Recursively remove all adjacent duplicates", link: "https://practice.geeksforgeeks.org/problems/consecutive-elements/0", difficulty: "Easy", tags: ["string", "stack", "recursion"] },
        { title: "String matching where one string contains wildcard characters", link: "https://practice.geeksforgeeks.org/problems/wildcard-string-matching/0", difficulty: "Hard", tags: ["string", "dp"] },
        { title: "Function to find Number of customers who could not get a computer", link: "https://www.geeksforgeeks.org/function-to-find-number-of-customers-who-could-not-get-a-computer/", difficulty: "Easy", tags: ["string", "queue"] },
        { title: "Transform One String to Another using Minimum Number of Given Operations", link: "https://www.geeksforgeeks.org/transform-one-string-to-another-using-minimum-number-of-given-operation/", difficulty: "Medium", tags: ["string", "sorting"] },
        { title: "Check if two given strings are isomorphic to each other", link: "https://practice.geeksforgeeks.org/problems/isomorphic-strings/0", difficulty: "Easy", tags: ["string", "hashmap"] },
        { title: "Recursively print all sentences from list of word lists", link: "https://www.geeksforgeeks.org/recursively-print-all-sentences-that-can-be-formed-from-list-of-word-lists/", difficulty: "Medium", tags: ["string", "recursion"] }
      ]
    },
    {
      title: "Searching & Sorting",
      problems: [
        { title: "Find first and last positions of an element in a sorted array", link: "https://practice.geeksforgeeks.org/problems/first-and-last-occurrences-of-x/0", difficulty: "Easy", tags: ["array", "binary-search"] },
        { title: "Find a Fixed Point (Value equal to index) in a given array", link: "https://practice.geeksforgeeks.org/problems/value-equal-to-index-value1330/1", difficulty: "Easy", tags: ["array", "binary-search"] },
        { title: "Search in a rotated sorted array", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/", difficulty: "Medium", tags: ["array", "binary-search"] },
        { title: "Square root of an integer", link: "https://practice.geeksforgeeks.org/problems/count-squares3649/1", difficulty: "Easy", tags: ["math", "binary-search"] },
        { title: "Maximum and minimum of an array using minimum number of comparisons", link: "https://practice.geeksforgeeks.org/problems/middle-of-three2926/1", difficulty: "Easy", tags: ["array", "divide-and-conquer"] },
        { title: "Optimum location of point to minimize total distance", link: "https://www.geeksforgeeks.org/optimum-location-point-minimize-total-distance/", difficulty: "Medium", tags: ["binary-search", "math"] },
        { title: "Find the repeating and the missing element", link: "https://practice.geeksforgeeks.org/problems/find-missing-and-repeating2512/1", difficulty: "Medium", tags: ["array", "math", "bit-manipulation"] },
        { title: "Find majority element", link: "https://practice.geeksforgeeks.org/problems/majority-element/0", difficulty: "Easy", tags: ["array", "voting-algorithm"] },
        { title: "Searching in an array where adjacent differ by at most k", link: "https://www.geeksforgeeks.org/searching-array-adjacent-differ-k/", difficulty: "Easy", tags: ["array", "linear-search"] },
        { title: "Find a pair with a given difference", link: "https://practice.geeksforgeeks.org/problems/find-pair-given-difference/0", difficulty: "Easy", tags: ["array", "binary-search", "two-pointers"] },
        { title: "Find four elements that sum to a given value", link: "https://practice.geeksforgeeks.org/problems/find-all-four-sum-numbers/0", difficulty: "Medium", tags: ["array", "two-pointers", "hashing"] },
        { title: "Maximum sum such that no 2 elements are adjacent", link: "https://practice.geeksforgeeks.org/problems/stickler-theif/0", difficulty: "Medium", tags: ["array", "dp"] },
        { title: "Count triplets with sum smaller than a given value", link: "https://practice.geeksforgeeks.org/problems/count-triplets-with-sum-smaller-than-x5549/1", difficulty: "Medium", tags: ["array", "two-pointers", "sorting"] },
        { title: "Merge 2 sorted arrays", link: "https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays5135/1", difficulty: "Hard", tags: ["array", "sorting"] },
        { title: "Print all subarrays with 0 sum", link: "https://practice.geeksforgeeks.org/problems/zero-sum-subarrays/0", difficulty: "Medium", tags: ["array", "hashmap", "prefix-sum"] },
        { title: "Product array Puzzle", link: "https://practice.geeksforgeeks.org/problems/product-array-puzzle/0", difficulty: "Easy", tags: ["array", "math"] },
        { title: "Sort array according to count of set bits", link: "https://practice.geeksforgeeks.org/problems/sort-by-set-bit-count/0", difficulty: "Easy", tags: ["array", "bit-manipulation", "sorting"] },
        { title: "Minimum number of swaps required to sort the array", link: "https://practice.geeksforgeeks.org/problems/minimum-swaps/1", difficulty: "Medium", tags: ["array", "graph", "sorting"] },
        { title: "Bishu and Soldiers", link: "https://www.hackerearth.com/practice/algorithms/searching/binary-search/practice-problems/algorithm/bishu-and-soldiers/", difficulty: "Easy", tags: ["binary-search"] },
        { title: "Rasta and Kheshtak", link: "https://www.hackerearth.com/practice/algorithms/searching/binary-search/practice-problems/algorithm/rasta-and-kheshtak/", difficulty: "Medium", tags: ["binary-search"] },
        { title: "Kth smallest number again", link: "https://www.hackerearth.com/practice/algorithms/searching/binary-search/practice-problems/algorithm/kth-smallest-number-again-2/", difficulty: "Medium", tags: ["binary-search"] },
        { title: "Find pivot element in a sorted and rotated array", link: "http://theoryofprogramming.com/2017/12/16/find-pivot-element-sorted-rotated-array/", difficulty: "Easy", tags: ["array", "binary-search"] },
        { title: "K-th Element of Two Sorted Arrays", link: "https://practice.geeksforgeeks.org/problems/kth-element-of-two-sorted-array/0", difficulty: "Hard", tags: ["array", "binary-search"] },
        { title: "Aggressive cows (SPOJ)", link: "https://www.spoj.com/problems/AGGRCOW/", difficulty: "Medium", tags: ["binary-search", "greedy"] },
        { title: "Book Allocation Problem", link: "https://practice.geeksforgeeks.org/problems/allocate-minimum-number-of-pages/0", difficulty: "Hard", tags: ["binary-search"] },
        { title: "EKOSPOJ", link: "https://www.spoj.com/problems/EKO/", difficulty: "Medium", tags: ["binary-search"] },
        { title: "Job Scheduling Algorithm", link: "https://www.geeksforgeeks.org/weighted-job-scheduling-log-n-time/", difficulty: "Hard", tags: ["dp", "binary-search"] },
        { title: "Missing Number in AP", link: "https://practice.geeksforgeeks.org/problems/arithmetic-number/0", difficulty: "Easy", tags: ["array", "binary-search", "math"] },
        { title: "Smallest number with at least n trailing zeroes in factorial", link: "https://practice.geeksforgeeks.org/problems/smallest-factorial-number5929/1", difficulty: "Medium", tags: ["binary-search", "math"] },
        { title: "Painters Partition Problem", link: "https://practice.geeksforgeeks.org/problems/allocate-minimum-number-of-pages/0", difficulty: "Hard", tags: ["binary-search", "dp"] },
        { title: "ROTI-Prata (SPOJ)", link: "https://www.spoj.com/problems/PRATA/", difficulty: "Medium", tags: ["binary-search"] },
        { title: "DoubleHelix SPOJ", link: "https://www.spoj.com/problems/ANARC05B/", difficulty: "Medium", tags: ["binary-search", "dp"] },
        { title: "Subset Sums (SPOJ)", link: "https://www.spoj.com/problems/SUBSUMS/", difficulty: "Medium", tags: ["binary-search", "sorting"] },
        { title: "Find the inversion count", link: "https://practice.geeksforgeeks.org/problems/inversion-of-array/0", difficulty: "Medium", tags: ["array", "merge-sort"] },
        { title: "Implement Merge Sort in-place", link: "https://www.geeksforgeeks.org/in-place-merge-sort/", difficulty: "Hard", tags: ["array", "sorting"] },
        { title: "Partitioning and Sorting Arrays with Many Repeated Entries", link: "https://www.baeldung.com/java-sorting-arrays-with-repeated-entries", difficulty: "Medium", tags: ["array", "sorting"] }
      ]
    },
    {
      title: "Linked List",
      problems: [
        { title: "Reverse the Linked List (Iterative and Recursive)", link: "https://www.geeksforgeeks.org/reverse-a-linked-list/", difficulty: "Easy", tags: ["linked-list", "recursion"] },
        { title: "Reverse a Linked List in groups of Given Size", link: "https://practice.geeksforgeeks.org/problems/reverse-a-linked-list-in-groups-of-given-size/1", difficulty: "Medium", tags: ["linked-list", "recursion"] },
        { title: "Detect loop in a linked list", link: "https://practice.geeksforgeeks.org/problems/detect-loop-in-linked-list/1", difficulty: "Easy", tags: ["linked-list", "two-pointers"] },
        { title: "Delete loop in a linked list", link: "https://practice.geeksforgeeks.org/problems/remove-loop-in-linked-list/1", difficulty: "Medium", tags: ["linked-list", "two-pointers"] },
        { title: "Find the starting point of the loop in a linked list", link: "https://www.geeksforgeeks.org/find-first-node-of-loop-in-a-linked-list/", difficulty: "Medium", tags: ["linked-list", "two-pointers"] },
        { title: "Remove Duplicates in a sorted Linked List", link: "https://practice.geeksforgeeks.org/problems/remove-duplicate-element-from-sorted-linked-list/1", difficulty: "Easy", tags: ["linked-list"] },
        { title: "Remove Duplicates in an Unsorted Linked List", link: "https://practice.geeksforgeeks.org/problems/remove-duplicates-from-an-unsorted-linked-list/1", difficulty: "Easy", tags: ["linked-list", "hashset"] },
        { title: "Move the last element to Front in a Linked List", link: "https://www.geeksforgeeks.org/move-last-element-to-front-of-a-given-linked-list/", difficulty: "Easy", tags: ["linked-list"] },
        { title: "Add 1 to a number represented as a Linked List", link: "https://practice.geeksforgeeks.org/problems/add-1-to-a-number-represented-as-linked-list/1", difficulty: "Medium", tags: ["linked-list", "recursion"] },
        { title: "Add two numbers represented by linked lists", link: "https://practice.geeksforgeeks.org/problems/add-two-numbers-represented-by-linked-lists/1", difficulty: "Medium", tags: ["linked-list", "math"] },
        { title: "Intersection of two Sorted Linked Lists", link: "https://practice.geeksforgeeks.org/problems/intersection-of-two-sorted-linked-lists/1", difficulty: "Easy", tags: ["linked-list", "two-pointers"] },
        { title: "Intersection Point of two Linked Lists", link: "https://practice.geeksforgeeks.org/problems/intersection-point-in-y-shaped-linked-lists/1", difficulty: "Easy", tags: ["linked-list", "two-pointers", "hashset"] },
        { title: "Merge Sort For Linked Lists", link: "https://practice.geeksforgeeks.org/problems/sort-a-linked-list/1", difficulty: "Hard", tags: ["linked-list", "divide-and-conquer"] },
        { title: "Quicksort for Linked Lists", link: "https://practice.geeksforgeeks.org/problems/quick-sort-on-linked-list/1", difficulty: "Hard", tags: ["linked-list", "sorting"] },
        { title: "Find the middle Element of a linked list", link: "https://leetcode.com/problems/middle-of-the-linked-list/", difficulty: "Easy", tags: ["linked-list", "two-pointers"] },
        { title: "Check if a linked list is a circular linked list", link: "https://practice.geeksforgeeks.org/problems/circular-linked-list/1", difficulty: "Easy", tags: ["linked-list"] },
        { title: "Split a Circular linked list into two halves", link: "https://practice.geeksforgeeks.org/problems/split-a-circular-linked-list-into-two-halves/1", difficulty: "Medium", tags: ["linked-list"] },
        { title: "Check whether a Singly Linked list is a palindrome or not", link: "https://practice.geeksforgeeks.org/problems/check-if-linked-list-is-pallindrome/1", difficulty: "Medium", tags: ["linked-list", "two-pointers", "recursion"] },
        { title: "Deletion from a Circular Linked List", link: "https://www.geeksforgeeks.org/deletion-circular-linked-list/", difficulty: "Easy", tags: ["linked-list"] },
        { title: "Reverse a Doubly Linked List", link: "https://practice.geeksforgeeks.org/problems/reverse-a-doubly-linked-list/1", difficulty: "Easy", tags: ["linked-list"] },
        { title: "Find pairs with a given sum in a DLL", link: "https://www.geeksforgeeks.org/find-pairs-given-sum-doubly-linked-list/", difficulty: "Easy", tags: ["linked-list", "two-pointers"] },
        { title: "Count triplets in a sorted DLL whose sum is equal to given value X", link: "https://www.geeksforgeeks.org/count-triplets-sorted-doubly-linked-list-whose-sum-equal-given-value-x/", difficulty: "Medium", tags: ["linked-list", "two-pointers"] },
        { title: "Sort a k-sorted Doubly Linked List", link: "https://www.geeksforgeeks.org/sort-k-sorted-doubly-linked-list/", difficulty: "Medium", tags: ["linked-list", "heap"] },
        { title: "Rotate Doubly Linked List by N nodes", link: "https://www.geeksforgeeks.org/rotate-doubly-linked-list-n-nodes/", difficulty: "Medium", tags: ["linked-list"] },
        { title: "Rotate a Doubly Linked List in groups of Given Size", link: "https://www.geeksforgeeks.org/reverse-doubly-linked-list-groups-given-size/", difficulty: "Hard", tags: ["linked-list", "recursion"] },
        { title: "Can we reverse a linked list in less than O(n)?", link: "https://www.geeksforgeeks.org/can-we-reverse-a-linked-list-in-less-than-on/", difficulty: "Hard", tags: ["linked-list", "theory"] },
        { title: "Why Quicksort is preferred for Arrays and Merge Sort for LinkedLists?", link: "https://www.geeksforgeeks.org/why-quick-sort-preferred-for-arrays-and-merge-sort-for-linked-lists/", difficulty: "Easy", tags: ["linked-list", "theory"] },
        { title: "Flatten a Linked List", link: "https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1", difficulty: "Medium", tags: ["linked-list", "merge-sort"] },
        { title: "Sort a LL of 0s, 1s and 2s", link: "https://practice.geeksforgeeks.org/problems/given-a-linked-list-of-0s-1s-and-2s-sort-it/1", difficulty: "Easy", tags: ["linked-list"] },
        { title: "Clone a linked list with next and random pointer", link: "https://practice.geeksforgeeks.org/problems/clone-a-linked-list-with-next-and-random-pointer/1", difficulty: "Hard", tags: ["linked-list", "hashmap"] },
        { title: "Merge K sorted Linked Lists", link: "https://practice.geeksforgeeks.org/problems/merge-k-sorted-linked-lists/1", difficulty: "Hard", tags: ["linked-list", "heap", "divide-and-conquer"] },
        { title: "Multiply 2 numbers represented by Linked Lists", link: "https://practice.geeksforgeeks.org/problems/multiply-two-linked-lists/1", difficulty: "Easy", tags: ["linked-list", "math"] },
        { title: "Delete nodes which have a greater value on right side", link: "https://practice.geeksforgeeks.org/problems/delete-nodes-having-greater-value-on-right/1", difficulty: "Medium", tags: ["linked-list", "stack"] },
        { title: "Segregate even and odd nodes in a Linked List", link: "https://practice.geeksforgeeks.org/problems/segregate-even-and-odd-nodes-in-a-linked-list/0", difficulty: "Easy", tags: ["linked-list"] },
        { title: "Nth node from the end of a Linked List", link: "https://practice.geeksforgeeks.org/problems/nth-node-from-end-of-linked-list/1", difficulty: "Easy", tags: ["linked-list", "two-pointers"] },
        { title: "Find the first non-repeating character from a stream of characters", link: "https://practice.geeksforgeeks.org/problems/first-non-repeating-character-in-a-stream/0", difficulty: "Medium", tags: ["linked-list", "queue", "hashmap"] }
      ]
    },
    {
      title: "Stacks & Queues",
      problems: [
        { title: "Implement Stack from Scratch", link: "https://www.tutorialspoint.com/javaexamples/data_stack.htm", difficulty: "Easy", tags: ["stack"] },
        { title: "Implement Queue from Scratch", link: "https://www.geeksforgeeks.org/queue-set-1introduction-and-array-implementation/", difficulty: "Easy", tags: ["queue"] },
        { title: "Implement 2 stacks in an array", link: "https://practice.geeksforgeeks.org/problems/implement-two-stacks-in-an-array/1", difficulty: "Easy", tags: ["stack", "array"] },
        { title: "Find the middle element of a stack", link: "https://www.geeksforgeeks.org/design-a-stack-with-find-middle-operation/", difficulty: "Medium", tags: ["stack", "linked-list"] },
        { title: "Implement N stacks in an Array", link: "https://www.geeksforgeeks.org/efficiently-implement-k-stacks-single-array/", difficulty: "Hard", tags: ["stack", "array"] },
        { title: "Check if expression has valid or balanced parentheses", link: "https://practice.geeksforgeeks.org/problems/parenthesis-checker/0", difficulty: "Easy", tags: ["stack", "string"] },
        { title: "Reverse a String using Stack", link: "https://practice.geeksforgeeks.org/problems/reverse-a-string-using-stack/1", difficulty: "Easy", tags: ["stack", "string"] },
        { title: "Design a Stack that supports getMin() in O(1) time and O(1) space", link: "https://practice.geeksforgeeks.org/problems/special-stack/1", difficulty: "Easy", tags: ["stack", "design"] },
        { title: "Find the next Greater Element", link: "https://practice.geeksforgeeks.org/problems/next-larger-element/0", difficulty: "Easy", tags: ["stack", "array"] },
        { title: "The Celebrity Problem", link: "https://practice.geeksforgeeks.org/problems/the-celebrity-problem/1", difficulty: "Medium", tags: ["stack", "graph"] },
        { title: "Arithmetic Expression Evaluation", link: "https://www.geeksforgeeks.org/arithmetic-expression-evalution/", difficulty: "Hard", tags: ["stack", "string"] },
        { title: "Evaluation of Postfix expression", link: "https://practice.geeksforgeeks.org/problems/evaluation-of-postfix-expression/0", difficulty: "Easy", tags: ["stack", "string"] },
        { title: "Insert an element at its bottom without using any other data structure", link: "https://stackoverflow.com/questions/45130465/inserting-at-the-end-of-stack", difficulty: "Easy", tags: ["stack", "recursion"] },
        { title: "Reverse a stack using recursion", link: "https://www.geeksforgeeks.org/reverse-a-stack-using-recursion/", difficulty: "Easy", tags: ["stack", "recursion"] },
        { title: "Sort a Stack using recursion", link: "https://practice.geeksforgeeks.org/problems/sort-a-stack/1", difficulty: "Medium", tags: ["stack", "recursion"] },
        { title: "Merge Overlapping Intervals", link: "https://practice.geeksforgeeks.org/problems/overlapping-intervals/0", difficulty: "Medium", tags: ["array", "stack", "sorting"] },
        { title: "Largest Rectangular Area in Histogram", link: "https://practice.geeksforgeeks.org/problems/maximum-rectangular-area-in-a-histogram/0", difficulty: "Hard", tags: ["stack", "array"] },
        { title: "Length of the Longest Valid Substring", link: "https://practice.geeksforgeeks.org/problems/valid-substring0624/1", difficulty: "Medium", tags: ["stack", "string"] },
        { title: "Expression contains redundant bracket or not", link: "https://www.geeksforgeeks.org/expression-contains-redundant-bracket-not/", difficulty: "Medium", tags: ["stack", "string"] },
        { title: "Implement Stack using Queue", link: "https://practice.geeksforgeeks.org/problems/stack-using-two-queues/1", difficulty: "Easy", tags: ["stack", "queue", "design"] },
        { title: "Implement Stack using Deque", link: "https://www.geeksforgeeks.org/implement-stackqueue-using-deque/", difficulty: "Easy", tags: ["stack", "deque", "design"] },
        { title: "Stack Permutations (Check if an array is stack permutation of other)", link: "https://www.geeksforgeeks.org/stack-permutations-check-if-an-array-is-stack-permutation-of-other/", difficulty: "Medium", tags: ["stack"] },
        { title: "Implement Queue using Stack", link: "https://practice.geeksforgeeks.org/problems/queue-using-two-stacks/1", difficulty: "Easy", tags: ["stack", "queue", "design"] },
        { title: "Implement n queues in an array", link: "https://www.geeksforgeeks.org/efficiently-implement-k-queues-single-array/", difficulty: "Hard", tags: ["queue", "array"] },
        { title: "Implement a Circular Queue", link: "https://www.geeksforgeeks.org/circular-queue-set-1-introduction-array-implementation/", difficulty: "Easy", tags: ["queue", "array"] },
        { title: "LRU Cache Implementation", link: "https://practice.geeksforgeeks.org/problems/lru-cache/1", difficulty: "Hard", tags: ["queue", "hashmap", "linked-list", "design"] },
        { title: "Reverse a Queue using recursion", link: "https://practice.geeksforgeeks.org/problems/queue-reversal/1", difficulty: "Easy", tags: ["queue", "recursion"] },
        { title: "Reverse the first K elements of a queue", link: "https://practice.geeksforgeeks.org/problems/reverse-first-k-elements-of-queue/1", difficulty: "Easy", tags: ["queue", "stack"] },
        { title: "Interleave the first half of the queue with second half", link: "https://www.geeksforgeeks.org/interleave-first-half-queue-second-half/", difficulty: "Medium", tags: ["queue"] },
        { title: "Find the first circular tour that visits all Petrol Pumps", link: "https://practice.geeksforgeeks.org/problems/circular-tour/1", difficulty: "Medium", tags: ["queue", "greedy"] },
        { title: "Minimum time required to rot all oranges", link: "https://practice.geeksforgeeks.org/problems/rotten-oranges/0", difficulty: "Medium", tags: ["queue", "bfs", "matrix"] },
        { title: "Distance of nearest cell having 1 in a binary matrix", link: "https://practice.geeksforgeeks.org/problems/distance-of-nearest-cell-having-1/0", difficulty: "Medium", tags: ["queue", "bfs", "matrix"] },
        { title: "First negative integer in every window of size k", link: "https://practice.geeksforgeeks.org/problems/first-negative-integer-in-every-window-of-size-k/0", difficulty: "Easy", tags: ["queue", "sliding-window"] },
        { title: "Check if all levels of two trees are anagrams or not", link: "https://www.geeksforgeeks.org/check-if-all-levels-of-two-trees-are-anagrams-or-not/", difficulty: "Easy", tags: ["queue", "bfs", "tree"] },
        { title: "Sum of minimum and maximum elements of all subarrays of size k", link: "https://www.geeksforgeeks.org/sum-minimum-maximum-elements-subarrays-size-k/", difficulty: "Medium", tags: ["queue", "deque", "sliding-window"] },
        { title: "Minimum sum of squares of character counts after removing k characters", link: "https://practice.geeksforgeeks.org/problems/game-with-string/0", difficulty: "Medium", tags: ["queue", "heap", "greedy"] },
        { title: "Queue based approach for first non-repeating character in a stream", link: "https://practice.geeksforgeeks.org/problems/first-non-repeating-character-in-a-stream/0", difficulty: "Easy", tags: ["queue", "hashmap"] },
        { title: "Next Smaller Element", link: "https://www.geeksforgeeks.org/next-smaller-element/", difficulty: "Easy", tags: ["stack", "array"] }
      ]
    },
    {
      title: "Binary Tree",
      problems: [
        { title: "Level order traversal", link: "https://practice.geeksforgeeks.org/problems/level-order-traversal/1", difficulty: "Easy", tags: ["tree", "bfs"] },
        { title: "Reverse Level Order traversal", link: "https://practice.geeksforgeeks.org/problems/reverse-level-order-traversal/1", difficulty: "Easy", tags: ["tree", "bfs"] },
        { title: "Height of a tree", link: "https://practice.geeksforgeeks.org/problems/height-of-binary-tree/1", difficulty: "Easy", tags: ["tree", "dfs", "recursion"] },
        { title: "Diameter of a tree", link: "https://practice.geeksforgeeks.org/problems/diameter-of-binary-tree/1", difficulty: "Easy", tags: ["tree", "dfs", "recursion"] },
        { title: "Mirror of a tree", link: "https://www.geeksforgeeks.org/create-a-mirror-tree-from-the-given-binary-tree/", difficulty: "Easy", tags: ["tree", "recursion"] },
        { title: "Inorder Traversal (Recursive and Iterative)", link: "https://www.techiedelight.com/inorder-tree-traversal-iterative-recursive/", difficulty: "Easy", tags: ["tree", "dfs", "stack"] },
        { title: "Preorder Traversal (Recursive and Iterative)", link: "https://www.techiedelight.com/preorder-tree-traversal-iterative-recursive/", difficulty: "Easy", tags: ["tree", "dfs", "stack"] },
        { title: "Postorder Traversal (Recursive and Iterative)", link: "https://www.techiedelight.com/postorder-tree-traversal-iterative-recursive/", difficulty: "Medium", tags: ["tree", "dfs", "stack"] },
        { title: "Left View of a tree", link: "https://practice.geeksforgeeks.org/problems/left-view-of-binary-tree/1", difficulty: "Easy", tags: ["tree", "bfs", "dfs"] },
        { title: "Right View of a tree", link: "https://practice.geeksforgeeks.org/problems/right-view-of-binary-tree/1", difficulty: "Easy", tags: ["tree", "bfs", "dfs"] },
        { title: "Top View of a tree", link: "https://practice.geeksforgeeks.org/problems/top-view-of-binary-tree/1", difficulty: "Medium", tags: ["tree", "bfs", "hashmap"] },
        { title: "Bottom View of a tree", link: "https://practice.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1", difficulty: "Medium", tags: ["tree", "bfs", "hashmap"] },
        { title: "Zig-Zag traversal of a binary tree", link: "https://practice.geeksforgeeks.org/problems/zigzag-tree-traversal/1", difficulty: "Medium", tags: ["tree", "bfs", "deque"] },
        { title: "Check if a tree is balanced or not", link: "https://practice.geeksforgeeks.org/problems/check-for-balanced-tree/1", difficulty: "Easy", tags: ["tree", "dfs", "recursion"] },
        { title: "Diagonal Traversal of a Binary tree", link: "https://www.geeksforgeeks.org/diagonal-traversal-of-binary-tree/", difficulty: "Medium", tags: ["tree", "bfs", "hashmap"] },
        { title: "Boundary traversal of a Binary tree", link: "https://practice.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1", difficulty: "Medium", tags: ["tree", "dfs"] },
        { title: "Construct Binary Tree from String with Bracket Representation", link: "https://www.geeksforgeeks.org/construct-binary-tree-string-bracket-representation/", difficulty: "Medium", tags: ["tree", "stack", "string"] },
        { title: "Convert Binary Tree into Doubly Linked List", link: "https://practice.geeksforgeeks.org/problems/binary-tree-to-dll/1", difficulty: "Hard", tags: ["tree", "dfs", "linked-list"] },
        { title: "Convert Binary Tree into Sum tree", link: "https://practice.geeksforgeeks.org/problems/transform-to-sum-tree/1", difficulty: "Easy", tags: ["tree", "dfs", "recursion"] },
        { title: "Construct Binary Tree from Inorder and Preorder traversal", link: "https://practice.geeksforgeeks.org/problems/construct-tree-1/1", difficulty: "Medium", tags: ["tree", "recursion", "hashmap"] },
        { title: "Find minimum swaps required to convert a Binary tree into BST", link: "https://www.geeksforgeeks.org/minimum-swap-required-convert-binary-tree-binary-search-tree/", difficulty: "Medium", tags: ["tree", "sorting"] },
        { title: "Check if Binary tree is Sum tree or not", link: "https://practice.geeksforgeeks.org/problems/sum-tree/1", difficulty: "Easy", tags: ["tree", "dfs", "recursion"] },
        { title: "Check if all leaf nodes are at same level or not", link: "https://practice.geeksforgeeks.org/problems/leaf-at-same-level/1", difficulty: "Easy", tags: ["tree", "bfs", "dfs"] },
        { title: "Check if a Binary Tree contains duplicate subtrees of size 2 or more", link: "https://practice.geeksforgeeks.org/problems/duplicate-subtree-in-binary-tree/1", difficulty: "Medium", tags: ["tree", "hashing", "serialization"] },
        { title: "Check if 2 trees are mirror or not", link: "https://practice.geeksforgeeks.org/problems/check-mirror-in-n-ary-tree/0", difficulty: "Easy", tags: ["tree", "recursion"] },
        { title: "Sum of Nodes on the Longest path from root to leaf node", link: "https://practice.geeksforgeeks.org/problems/sum-of-the-longest-bloodline-of-a-tree/1", difficulty: "Medium", tags: ["tree", "dfs", "recursion"] },
        { title: "Check if given graph is tree or not", link: "https://www.geeksforgeeks.org/check-given-graph-tree/", difficulty: "Medium", tags: ["tree", "graph", "dfs"] },
        { title: "Find Largest subtree sum in a tree", link: "https://www.geeksforgeeks.org/find-largest-subtree-sum-tree/", difficulty: "Easy", tags: ["tree", "dfs", "recursion"] },
        { title: "Maximum Sum of nodes in Binary tree such that no two are adjacent", link: "https://www.geeksforgeeks.org/maximum-sum-nodes-binary-tree-no-two-adjacent/", difficulty: "Hard", tags: ["tree", "dp"] },
        { title: "Print all K Sum paths in a Binary tree", link: "https://www.geeksforgeeks.org/print-k-sum-paths-binary-tree/", difficulty: "Medium", tags: ["tree", "dfs", "hashmap"] },
        { title: "Find LCA in a Binary tree", link: "https://practice.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-binary-tree/1", difficulty: "Medium", tags: ["tree", "dfs", "recursion"] },
        { title: "Find distance between 2 nodes in a Binary tree", link: "https://practice.geeksforgeeks.org/problems/min-distance-between-two-given-nodes-of-a-binary-tree/1", difficulty: "Medium", tags: ["tree", "dfs", "lca"] },
        { title: "Kth Ancestor of node in a Binary tree", link: "https://www.geeksforgeeks.org/kth-ancestor-node-binary-tree-set-2/", difficulty: "Medium", tags: ["tree", "dfs", "recursion"] },
        { title: "Find all Duplicate subtrees in a Binary tree", link: "https://practice.geeksforgeeks.org/problems/duplicate-subtrees/1", difficulty: "Medium", tags: ["tree", "hashing", "serialization"] },
        { title: "Tree Isomorphism Problem", link: "https://practice.geeksforgeeks.org/problems/check-if-tree-is-isomorphic/1", difficulty: "Easy", tags: ["tree", "recursion"] }
      ]
    },
    {
      title: "Binary Search Tree",
      problems: [
        { title: "Find a value in a BST", link: "https://www.geeksforgeeks.org/binary-search-tree-set-1-search-and-insertion/", difficulty: "Easy", tags: ["bst", "recursion"] },
        { title: "Deletion of a node in a BST", link: "https://leetcode.com/problems/delete-node-in-a-bst/", difficulty: "Medium", tags: ["bst", "recursion"] },
        { title: "Find min and max value in a BST", link: "https://practice.geeksforgeeks.org/problems/minimum-element-in-bst/1", difficulty: "Easy", tags: ["bst"] },
        { title: "Find inorder successor and inorder predecessor in a BST", link: "https://practice.geeksforgeeks.org/problems/predecessor-and-successor/1", difficulty: "Easy", tags: ["bst", "inorder"] },
        { title: "Check if a tree is a BST or not", link: "https://practice.geeksforgeeks.org/problems/check-for-bst/1", difficulty: "Easy", tags: ["bst", "inorder", "recursion"] },
        { title: "Populate Inorder successor of all nodes", link: "https://practice.geeksforgeeks.org/problems/populate-inorder-successor-for-all-nodes/1", difficulty: "Medium", tags: ["bst", "inorder"] },
        { title: "Find LCA of 2 nodes in a BST", link: "https://practice.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-bst/1", difficulty: "Easy", tags: ["bst", "recursion"] },
        { title: "Construct BST from preorder traversal", link: "https://www.geeksforgeeks.org/construct-bst-from-given-preorder-traversal/", difficulty: "Medium", tags: ["bst", "stack"] },
        { title: "Convert Binary Tree into BST", link: "https://practice.geeksforgeeks.org/problems/binary-tree-to-bst/1", difficulty: "Medium", tags: ["bst", "inorder", "sorting"] },
        { title: "Convert a normal BST into a Balanced BST", link: "https://www.geeksforgeeks.org/convert-normal-bst-balanced-bst/", difficulty: "Medium", tags: ["bst", "inorder", "divide-and-conquer"] },
        { title: "Merge two BSTs", link: "https://www.geeksforgeeks.org/merge-two-balanced-binary-search-trees/", difficulty: "Hard", tags: ["bst", "inorder", "merge"] },
        { title: "Find Kth largest element in a BST", link: "https://practice.geeksforgeeks.org/problems/kth-largest-element-in-bst/1", difficulty: "Easy", tags: ["bst", "inorder"] },
        { title: "Find Kth smallest element in a BST", link: "https://practice.geeksforgeeks.org/problems/find-k-th-smallest-element-in-bst/1", difficulty: "Easy", tags: ["bst", "inorder"] },
        { title: "Count pairs from 2 BSTs whose sum is equal to given value X", link: "https://practice.geeksforgeeks.org/problems/brothers-from-different-root/1", difficulty: "Medium", tags: ["bst", "two-pointers"] },
        { title: "Find the median of BST in O(n) time and O(1) space", link: "https://www.geeksforgeeks.org/find-median-bst-time-o1-space/", difficulty: "Hard", tags: ["bst", "inorder"] },
        { title: "Count BST nodes that lie in a given range", link: "https://practice.geeksforgeeks.org/problems/count-bst-nodes-that-lie-in-a-given-range/1", difficulty: "Easy", tags: ["bst", "recursion"] },
        { title: "Replace every element with the least greater element on its right", link: "https://www.geeksforgeeks.org/replace-every-element-with-the-least-greater-element-on-its-right/", difficulty: "Medium", tags: ["bst", "array"] },
        { title: "Given n appointments, find the conflicting appointments", link: "https://www.geeksforgeeks.org/given-n-appointments-find-conflicting-appointments/", difficulty: "Medium", tags: ["bst", "interval", "sorting"] },
        { title: "Check preorder is valid or not", link: "https://practice.geeksforgeeks.org/problems/preorder-to-postorder/0", difficulty: "Medium", tags: ["bst", "stack"] },
        { title: "Check whether BST contains Dead End", link: "https://practice.geeksforgeeks.org/problems/check-whether-bst-contains-dead-end/1", difficulty: "Medium", tags: ["bst", "recursion", "hashset"] },
        { title: "Largest BST in a Binary Tree", link: "https://practice.geeksforgeeks.org/problems/largest-bst/1", difficulty: "Hard", tags: ["bst", "dp", "recursion"] },
        { title: "Flatten BST to sorted list", link: "https://www.geeksforgeeks.org/flatten-bst-to-sorted-list-increasing-order/", difficulty: "Medium", tags: ["bst", "inorder", "linked-list"] }
      ]
    },
    {
      title: "Greedy",
      problems: [
        { title: "Activity Selection Problem", link: "https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room/0", difficulty: "Easy", tags: ["greedy", "sorting"] },
        { title: "Job Sequencing Problem", link: "https://practice.geeksforgeeks.org/problems/job-sequencing-problem/0", difficulty: "Medium", tags: ["greedy", "sorting"] },
        { title: "Huffman Coding", link: "https://practice.geeksforgeeks.org/problems/huffman-encoding/0", difficulty: "Medium", tags: ["greedy", "heap", "tree"] },
        { title: "Water Connection Problem", link: "https://practice.geeksforgeeks.org/problems/water-connection-problem/0", difficulty: "Medium", tags: ["greedy", "graph"] },
        { title: "Fractional Knapsack Problem", link: "https://practice.geeksforgeeks.org/problems/fractional-knapsack/0", difficulty: "Medium", tags: ["greedy", "sorting"] },
        { title: "Greedy Algorithm to find Minimum number of Coins", link: "https://practice.geeksforgeeks.org/problems/coin-piles/0", difficulty: "Easy", tags: ["greedy"] },
        { title: "Maximum trains for which stoppage can be provided", link: "https://www.geeksforgeeks.org/maximum-trains-stoppage-can-provided/", difficulty: "Medium", tags: ["greedy", "sorting"] },
        { title: "Minimum Platforms Problem", link: "https://practice.geeksforgeeks.org/problems/minimum-platforms/0", difficulty: "Medium", tags: ["greedy", "sorting", "two-pointers"] },
        { title: "Buy Maximum Stocks if i stocks can be bought on i-th day", link: "https://www.geeksforgeeks.org/buy-maximum-stocks-stocks-can-bought-th-day/", difficulty: "Medium", tags: ["greedy", "sorting"] },
        { title: "Find the minimum and maximum amount to buy all N candies", link: "https://practice.geeksforgeeks.org/problems/shop-in-candy-store/0", difficulty: "Easy", tags: ["greedy", "sorting"] },
        { title: "Minimize Cash Flow among a given set of friends", link: "https://www.geeksforgeeks.org/minimize-cash-flow-among-given-set-friends-borrowed-money/", difficulty: "Hard", tags: ["greedy", "graph"] },
        { title: "Minimum Cost to cut a board into squares", link: "https://www.geeksforgeeks.org/minimum-cost-cut-board-squares/", difficulty: "Medium", tags: ["greedy", "sorting"] },
        { title: "Check if it is possible to survive on Island", link: "https://www.geeksforgeeks.org/survival/", difficulty: "Easy", tags: ["greedy"] },
        { title: "Find maximum meetings in one room", link: "https://www.geeksforgeeks.org/find-maximum-meetings-in-one-room/", difficulty: "Easy", tags: ["greedy", "sorting"] },
        { title: "Maximum product subset of an array", link: "https://www.geeksforgeeks.org/maximum-product-subset-array/", difficulty: "Medium", tags: ["greedy", "math"] },
        { title: "Maximize array sum after K negations", link: "https://practice.geeksforgeeks.org/problems/maximize-sum-after-k-negations/0", difficulty: "Easy", tags: ["greedy", "sorting"] },
        { title: "Maximize the sum of arr[i]*i", link: "https://practice.geeksforgeeks.org/problems/maximize-arrii-of-an-array/0", difficulty: "Easy", tags: ["greedy", "sorting"] },
        { title: "Maximum sum of absolute difference of an array", link: "https://www.geeksforgeeks.org/maximum-sum-absolute-difference-array/", difficulty: "Medium", tags: ["greedy", "sorting"] },
        { title: "Maximize sum of consecutive differences in a circular array", link: "https://practice.geeksforgeeks.org/problems/swap-and-maximize/0", difficulty: "Medium", tags: ["greedy", "sorting"] },
        { title: "Minimum sum of absolute difference of pairs of two arrays", link: "https://www.geeksforgeeks.org/minimum-sum-absolute-difference-pairs-two-arrays/", difficulty: "Easy", tags: ["greedy", "sorting"] },
        { title: "Program for Shortest Job First (SJF) CPU Scheduling", link: "https://www.geeksforgeeks.org/program-for-shortest-job-first-or-sjf-cpu-scheduling-set-1-non-preemptive/", difficulty: "Medium", tags: ["greedy", "sorting"] },
        { title: "Program for Least Recently Used (LRU) Page Replacement", link: "https://practice.geeksforgeeks.org/problems/page-faults-in-lru/0", difficulty: "Medium", tags: ["greedy", "design", "hashmap"] },
        { title: "Smallest subset with sum greater than all other elements", link: "https://www.geeksforgeeks.org/smallest-subset-sum-greater-elements/", difficulty: "Easy", tags: ["greedy", "sorting"] },
        { title: "Chocolate Distribution Problem", link: "https://practice.geeksforgeeks.org/problems/chocolate-distribution-problem/0", difficulty: "Easy", tags: ["greedy", "sorting"] },
        { title: "DEFKIN - Defense of a Kingdom (SPOJ)", link: "https://www.spoj.com/problems/DEFKIN/", difficulty: "Medium", tags: ["greedy"] },
        { title: "DIEHARD - DIE HARD (SPOJ)", link: "https://www.spoj.com/problems/DIEHARD/", difficulty: "Medium", tags: ["greedy", "dp"] },
        { title: "GERGOVIA - Wine trading in Gergovia (SPOJ)", link: "https://www.spoj.com/problems/GERGOVIA/", difficulty: "Medium", tags: ["greedy"] },
        { title: "Picking Up Chicks (SPOJ)", link: "https://www.spoj.com/problems/GCJ101BB/", difficulty: "Medium", tags: ["greedy"] },
        { title: "CHOCOLA - Chocolate (SPOJ)", link: "https://www.spoj.com/problems/CHOCOLA/", difficulty: "Medium", tags: ["greedy", "sorting"] },
        { title: "ARRANGE - Arranging Amplifiers (SPOJ)", link: "https://www.spoj.com/problems/ARRANGE/", difficulty: "Medium", tags: ["greedy"] },
        { title: "K Centers Problem", link: "https://www.geeksforgeeks.org/k-centers-problem-set-1-greedy-approximate-algorithm/", difficulty: "Hard", tags: ["greedy", "graph"] },
        { title: "Minimum Cost of ropes", link: "https://practice.geeksforgeeks.org/problems/minimum-cost-of-ropes/0", difficulty: "Easy", tags: ["greedy", "heap"] },
        { title: "Find smallest number with given number of digits and sum of digits", link: "https://practice.geeksforgeeks.org/problems/smallest-number5829/1", difficulty: "Medium", tags: ["greedy"] },
        { title: "Rearrange characters in a string such that no two adjacent are same", link: "https://practice.geeksforgeeks.org/problems/rearrange-characters/0", difficulty: "Medium", tags: ["greedy", "heap"] },
        { title: "Find maximum sum possible equal sum of three stacks", link: "https://www.geeksforgeeks.org/find-maximum-sum-possible-equal-sum-three-stacks/", difficulty: "Medium", tags: ["greedy", "stack"] }
      ]
    },
    {
      title: "Backtracking",
      problems: [
        { title: "Rat in a Maze Problem", link: "https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1", difficulty: "Medium", tags: ["backtracking", "matrix"] },
        { title: "Printing all solutions in N-Queen Problem", link: "https://www.geeksforgeeks.org/printing-solutions-n-queen-problem/", difficulty: "Hard", tags: ["backtracking"] },
        { title: "Word Break Problem using Backtracking", link: "https://practice.geeksforgeeks.org/problems/word-break-part-2/0", difficulty: "Hard", tags: ["backtracking", "dp", "string"] },
        { title: "Remove Invalid Parentheses", link: "https://leetcode.com/problems/remove-invalid-parentheses/", difficulty: "Hard", tags: ["backtracking", "bfs", "string"] },
        { title: "Sudoku Solver", link: "https://practice.geeksforgeeks.org/problems/solve-the-sudoku/0", difficulty: "Hard", tags: ["backtracking", "matrix"] },
        { title: "m Coloring Problem", link: "https://practice.geeksforgeeks.org/problems/m-coloring-problem/0", difficulty: "Medium", tags: ["backtracking", "graph"] },
        { title: "Print all palindromic partitions of a string", link: "https://www.geeksforgeeks.org/given-a-string-print-all-possible-palindromic-partition/", difficulty: "Hard", tags: ["backtracking", "dp", "string"] },
        { title: "Subset Sum Problem", link: "https://practice.geeksforgeeks.org/problems/subset-sum-problem2014/1", difficulty: "Medium", tags: ["backtracking", "dp"] },
        { title: "The Knight's Tour problem", link: "https://www.geeksforgeeks.org/the-knights-tour-problem-backtracking-1/", difficulty: "Hard", tags: ["backtracking", "matrix"] },
        { title: "Tug of War", link: "https://www.geeksforgeeks.org/tug-of-war/", difficulty: "Medium", tags: ["backtracking"] },
        { title: "Find shortest safe route in a path with landmines", link: "https://www.geeksforgeeks.org/find-shortest-safe-route-in-a-path-with-landmines/", difficulty: "Hard", tags: ["backtracking", "matrix", "bfs"] },
        { title: "Combination Sum", link: "https://practice.geeksforgeeks.org/problems/combination-sum/0", difficulty: "Medium", tags: ["backtracking", "recursion"] },
        { title: "Find Maximum number possible by doing at-most K swaps", link: "https://practice.geeksforgeeks.org/problems/largest-number-in-k-swaps/0", difficulty: "Medium", tags: ["backtracking", "greedy"] },
        { title: "Print all permutations of a string", link: "https://practice.geeksforgeeks.org/problems/permutations-of-a-given-string/0", difficulty: "Medium", tags: ["backtracking", "recursion", "string"] },
        { title: "Find if there is a path of more than k length from a source", link: "https://www.geeksforgeeks.org/find-if-there-is-a-path-of-more-than-k-length-from-a-source/", difficulty: "Medium", tags: ["backtracking", "graph"] },
        { title: "Longest Possible Route in a Matrix with Hurdles", link: "https://www.geeksforgeeks.org/longest-possible-route-in-a-matrix-with-hurdles/", difficulty: "Hard", tags: ["backtracking", "matrix"] },
        { title: "Print all possible paths from top left to bottom right of a mXn matrix", link: "https://www.geeksforgeeks.org/print-all-possible-paths-from-top-left-to-bottom-right-of-a-mxn-matrix/", difficulty: "Medium", tags: ["backtracking", "matrix"] },
        { title: "Partition of a set into K subsets with equal sum", link: "https://practice.geeksforgeeks.org/problems/partition-array-to-k-subsets/1", difficulty: "Hard", tags: ["backtracking", "dp"] },
        { title: "Find the K-th Permutation Sequence of first N natural numbers", link: "https://www.geeksforgeeks.org/find-the-k-th-permutation-sequence-of-first-n-natural-numbers/", difficulty: "Medium", tags: ["backtracking", "math"] }
      ]
    },
    {
      title: "Dynamic Programming",
      problems: [
        { title: "Coin Change Problem", link: "https://practice.geeksforgeeks.org/problems/coin-change2448/1", difficulty: "Medium", tags: ["dp", "array"] },
        { title: "0-1 Knapsack Problem", link: "https://practice.geeksforgeeks.org/problems/0-1-knapsack-problem/0", difficulty: "Medium", tags: ["dp", "array"] },
        { title: "Binomial Coefficient Problem", link: "https://practice.geeksforgeeks.org/problems/ncr1019/1", difficulty: "Easy", tags: ["dp", "math"] },
        { title: "Permutation Coefficient Problem", link: "https://www.geeksforgeeks.org/permutation-coefficient/", difficulty: "Easy", tags: ["dp", "math"] },
        { title: "Program for nth Catalan Number", link: "https://www.geeksforgeeks.org/program-nth-catalan-number/", difficulty: "Easy", tags: ["dp", "math"] },
        { title: "Matrix Chain Multiplication", link: "https://www.geeksforgeeks.org/matrix-chain-multiplication-dp-8/", difficulty: "Hard", tags: ["dp", "matrix"] },
        { title: "Edit Distance", link: "https://practice.geeksforgeeks.org/problems/edit-distance3702/1", difficulty: "Hard", tags: ["dp", "string"] },
        { title: "Subset Sum Problem", link: "https://practice.geeksforgeeks.org/problems/subset-sum-problem2014/1", difficulty: "Medium", tags: ["dp", "array"] },
        { title: "Friends Pairing Problem", link: "https://practice.geeksforgeeks.org/problems/friends-pairing-problem5425/1", difficulty: "Easy", tags: ["dp"] },
        { title: "Gold Mine Problem", link: "https://www.geeksforgeeks.org/gold-mine-problem/", difficulty: "Medium", tags: ["dp", "matrix"] },
        { title: "Assembly Line Scheduling Problem", link: "https://www.geeksforgeeks.org/assembly-line-scheduling-dp-34/", difficulty: "Medium", tags: ["dp"] },
        { title: "Painting the Fence problem", link: "https://practice.geeksforgeeks.org/problems/painting-the-fence3727/1", difficulty: "Medium", tags: ["dp", "math"] },
        { title: "Maximize The Cut Segments", link: "https://practice.geeksforgeeks.org/problems/cutted-segments/0", difficulty: "Medium", tags: ["dp"] },
        { title: "Longest Common Subsequence", link: "https://practice.geeksforgeeks.org/problems/longest-common-subsequence/0", difficulty: "Medium", tags: ["dp", "string"] },
        { title: "Longest Repeated Subsequence", link: "https://practice.geeksforgeeks.org/problems/longest-repeating-subsequence/0", difficulty: "Easy", tags: ["dp", "string"] },
        { title: "Longest Increasing Subsequence", link: "https://practice.geeksforgeeks.org/problems/longest-increasing-subsequence/0", difficulty: "Medium", tags: ["dp", "array", "binary-search"] },
        { title: "Space Optimized Solution of LCS", link: "https://www.geeksforgeeks.org/space-optimized-solution-lcs/", difficulty: "Medium", tags: ["dp", "string"] },
        { title: "LCS of three strings", link: "https://practice.geeksforgeeks.org/problems/lcs-of-three-strings/0", difficulty: "Medium", tags: ["dp", "string"] },
        { title: "Maximum Sum Increasing Subsequence", link: "https://practice.geeksforgeeks.org/problems/maximum-sum-increasing-subsequence4749/1", difficulty: "Medium", tags: ["dp", "array"] },
        { title: "Count all subsequences having product less than K", link: "https://www.geeksforgeeks.org/count-subsequences-product-less-k/", difficulty: "Medium", tags: ["dp"] },
        { title: "Longest subsequence such that difference between adjacent is one", link: "https://practice.geeksforgeeks.org/problems/longest-subsequence-such-that-difference-between-adjacents-is-one4724/1", difficulty: "Medium", tags: ["dp", "array"] },
        { title: "Maximum subsequence sum such that no three are consecutive", link: "https://www.geeksforgeeks.org/maximum-subsequence-sum-such-that-no-three-are-consecutive/", difficulty: "Medium", tags: ["dp"] },
        { title: "Egg Dropping Problem", link: "https://practice.geeksforgeeks.org/problems/egg-dropping-puzzle/0", difficulty: "Hard", tags: ["dp"] },
        { title: "Maximum Length Chain of Pairs", link: "https://practice.geeksforgeeks.org/problems/max-length-chain/1", difficulty: "Medium", tags: ["dp", "sorting"] },
        { title: "Maximum size square sub-matrix with all 1s", link: "https://practice.geeksforgeeks.org/problems/largest-square-formed-in-a-matrix/0", difficulty: "Medium", tags: ["dp", "matrix"] },
        { title: "Maximum sum of pairs with specific difference", link: "https://practice.geeksforgeeks.org/problems/pairs-with-specific-difference/0", difficulty: "Medium", tags: ["dp", "sorting"] },
        { title: "Min Cost Path Problem", link: "https://practice.geeksforgeeks.org/problems/path-in-matrix3805/1", difficulty: "Medium", tags: ["dp", "matrix"] },
        { title: "Maximum difference of zeros and ones in binary string", link: "https://practice.geeksforgeeks.org/problems/maximum-difference-of-zeros-and-ones-in-binary-string4111/1", difficulty: "Easy", tags: ["dp", "string"] },
        { title: "Minimum number of jumps to reach end", link: "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0", difficulty: "Medium", tags: ["dp", "greedy"] },
        { title: "Minimum cost to fill given weight in a bag", link: "https://practice.geeksforgeeks.org/problems/minimum-cost-to-fill-given-weight-in-a-bag1956/1", difficulty: "Medium", tags: ["dp"] },
        { title: "Minimum removals from array to make max-min <= K", link: "https://www.geeksforgeeks.org/minimum-removals-array-make-max-min-k/", difficulty: "Hard", tags: ["dp", "sorting"] },
        { title: "Longest Common Substring", link: "https://practice.geeksforgeeks.org/problems/longest-common-substring/0", difficulty: "Medium", tags: ["dp", "string"] },
        { title: "Count number of ways to reach a given score in a game", link: "https://www.geeksforgeeks.org/count-number-ways-reach-given-score-game/", difficulty: "Medium", tags: ["dp"] },
        { title: "Count Balanced Binary Trees of height h", link: "https://practice.geeksforgeeks.org/problems/bbt-counter/0", difficulty: "Medium", tags: ["dp", "tree"] },
        { title: "Smallest sum contiguous subarray", link: "https://www.geeksforgeeks.org/smallest-sum-contiguous-subarray/", difficulty: "Easy", tags: ["dp", "array"] },
        { title: "Unbounded Knapsack (Repetition of items allowed)", link: "https://practice.geeksforgeeks.org/problems/knapsack-with-duplicate-items4201/1", difficulty: "Medium", tags: ["dp", "array"] },
        { title: "Word Break Problem", link: "https://practice.geeksforgeeks.org/problems/word-break/0", difficulty: "Medium", tags: ["dp", "string", "trie"] },
        { title: "Largest Independent Set Problem", link: "https://www.geeksforgeeks.org/largest-independent-set-problem-dp-26/", difficulty: "Hard", tags: ["dp", "tree"] },
        { title: "Partition problem", link: "https://practice.geeksforgeeks.org/problems/subset-sum-problem2014/1", difficulty: "Medium", tags: ["dp", "array"] },
        { title: "Longest Palindromic Subsequence", link: "https://www.geeksforgeeks.org/longest-palindromic-subsequence-dp-12/", difficulty: "Medium", tags: ["dp", "string"] },
        { title: "Count All Palindromic Subsequences in a given String", link: "https://practice.geeksforgeeks.org/problems/count-palindromic-subsequences/1", difficulty: "Hard", tags: ["dp", "string"] },
        { title: "Longest Palindromic Substring", link: "https://leetcode.com/problems/longest-palindromic-substring/", difficulty: "Medium", tags: ["dp", "string", "two-pointers"] },
        { title: "Longest Alternating Subsequence", link: "https://practice.geeksforgeeks.org/problems/longest-alternating-subsequence/0", difficulty: "Medium", tags: ["dp"] },
        { title: "Weighted Job Scheduling", link: "https://www.geeksforgeeks.org/weighted-job-scheduling/", difficulty: "Hard", tags: ["dp", "sorting", "binary-search"] },
        { title: "Coin game winner where every player has three choices", link: "https://www.geeksforgeeks.org/coin-game-winner-every-player-three-choices/", difficulty: "Medium", tags: ["dp", "game-theory"] },
        { title: "Count Derangements", link: "https://www.geeksforgeeks.org/count-derangements-permutation-such-that-no-element-appears-in-its-original-position/", difficulty: "Easy", tags: ["dp", "math"] },
        { title: "Maximum profit by buying and selling a share at most twice", link: "https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-twice/", difficulty: "Hard", tags: ["dp", "array"] },
        { title: "Optimal Strategy for a Game", link: "https://practice.geeksforgeeks.org/problems/optimal-strategy-for-a-game/0", difficulty: "Hard", tags: ["dp", "game-theory"] },
        { title: "Optimal Binary Search Tree", link: "https://www.geeksforgeeks.org/optimal-binary-search-tree-dp-24/", difficulty: "Hard", tags: ["dp", "tree"] },
        { title: "Palindrome Partitioning Problem", link: "https://practice.geeksforgeeks.org/problems/palindromic-patitioning4845/1", difficulty: "Hard", tags: ["dp", "string"] },
        { title: "Word Wrap Problem", link: "https://practice.geeksforgeeks.org/problems/word-wrap/0", difficulty: "Hard", tags: ["dp", "string"] },
        { title: "Mobile Numeric Keypad Problem", link: "https://practice.geeksforgeeks.org/problems/mobile-numeric-keypad5456/1", difficulty: "Medium", tags: ["dp"] },
        { title: "Boolean Parenthesization Problem", link: "https://practice.geeksforgeeks.org/problems/boolean-parenthesization/0", difficulty: "Hard", tags: ["dp", "string"] },
        { title: "Largest rectangular sub-matrix whose sum is 0", link: "https://www.geeksforgeeks.org/largest-rectangular-sub-matrix-whose-sum-0/", difficulty: "Hard", tags: ["dp", "matrix", "hashmap"] },
        { title: "Largest area rectangular sub-matrix with equal number of 1s and 0s", link: "https://www.geeksforgeeks.org/largest-area-rectangular-sub-matrix-equal-number-1s-0s/", difficulty: "Hard", tags: ["dp", "matrix"] },
        { title: "Maximum sum rectangle in a 2D matrix", link: "https://practice.geeksforgeeks.org/problems/maximum-sum-rectangle/0", difficulty: "Hard", tags: ["dp", "matrix", "kadane"] },
        { title: "Maximum profit by buying and selling a share at most k times", link: "https://practice.geeksforgeeks.org/problems/maximum-profit4657/1", difficulty: "Hard", tags: ["dp", "array"] },
        { title: "Find if a string is interleaved of two other strings", link: "https://practice.geeksforgeeks.org/problems/interleaved-strings/1", difficulty: "Medium", tags: ["dp", "string"] },
        { title: "Maximum Length of Pair Chain", link: "https://leetcode.com/problems/maximum-length-of-pair-chain/", difficulty: "Medium", tags: ["dp", "greedy", "sorting"] }
      ]
    },
    {
      title: "Heap",
      problems: [
        { title: "Implement a MaxHeap/MinHeap using arrays and recursion", link: "https://www.geeksforgeeks.org/building-heap-from-array/", difficulty: "Medium", tags: ["heap", "array"] },
        { title: "Sort an Array using heap (HeapSort)", link: "https://www.geeksforgeeks.org/heap-sort/", difficulty: "Medium", tags: ["heap", "sorting"] },
        { title: "Maximum of all subarrays of size k", link: "https://www.geeksforgeeks.org/sliding-window-maximum-maximum-of-all-subarrays-of-size-k/", difficulty: "Hard", tags: ["heap", "deque", "sliding-window"] },
        { title: "K largest elements in an array", link: "https://practice.geeksforgeeks.org/problems/k-largest-elements4206/1", difficulty: "Easy", tags: ["heap", "array"] },
        { title: "Kth smallest and largest element in an unsorted array", link: "https://www.geeksforgeeks.org/kth-smallestlargest-element-unsorted-array/", difficulty: "Medium", tags: ["heap", "quick-select"] },
        { title: "Merge K sorted arrays", link: "https://practice.geeksforgeeks.org/problems/merge-k-sorted-arrays/1", difficulty: "Medium", tags: ["heap", "divide-and-conquer"] },
        { title: "Merge 2 Binary Max Heaps", link: "https://practice.geeksforgeeks.org/problems/merge-two-binary-max-heap/0", difficulty: "Medium", tags: ["heap"] },
        { title: "Kth largest sum continuous subarrays", link: "https://www.geeksforgeeks.org/k-th-largest-sum-contiguous-subarray/", difficulty: "Medium", tags: ["heap", "prefix-sum"] },
        { title: "Reorganize Strings", link: "https://leetcode.com/problems/reorganize-string/", difficulty: "Medium", tags: ["heap", "greedy", "string"] },
        { title: "Merge K Sorted Linked Lists", link: "https://practice.geeksforgeeks.org/problems/merge-k-sorted-linked-lists/1", difficulty: "Hard", tags: ["heap", "linked-list"] },
        { title: "Smallest range in K Lists", link: "https://practice.geeksforgeeks.org/problems/find-smallest-range-containing-elements-from-k-lists/1", difficulty: "Hard", tags: ["heap", "sliding-window"] },
        { title: "Median in a stream of Integers", link: "https://practice.geeksforgeeks.org/problems/find-median-in-a-stream/0", difficulty: "Hard", tags: ["heap", "design"] },
        { title: "Check if a Binary Tree is Heap", link: "https://practice.geeksforgeeks.org/problems/is-binary-tree-heap/1", difficulty: "Easy", tags: ["heap", "tree"] },
        { title: "Connect n ropes with minimum cost", link: "https://practice.geeksforgeeks.org/problems/minimum-cost-of-ropes/0", difficulty: "Easy", tags: ["heap", "greedy"] },
        { title: "Convert BST to Min Heap", link: "https://www.geeksforgeeks.org/convert-bst-min-heap/", difficulty: "Medium", tags: ["heap", "bst"] },
        { title: "Convert min heap to max heap", link: "https://www.geeksforgeeks.org/convert-min-heap-to-max-heap/", difficulty: "Easy", tags: ["heap"] },
        { title: "Rearrange characters in a string such that no two adjacent are same", link: "https://practice.geeksforgeeks.org/problems/rearrange-characters/0", difficulty: "Medium", tags: ["heap", "greedy", "string"] },
        { title: "Minimum sum of two numbers formed from digits of an array", link: "https://practice.geeksforgeeks.org/problems/minimum-sum4058/1", difficulty: "Easy", tags: ["heap", "greedy"] }
      ]
    },
    {
      title: "Graph",
      problems: [
        { title: "Create a Graph and print it", link: "https://www.geeksforgeeks.org/graph-and-its-representations/", difficulty: "Easy", tags: ["graph"] },
        { title: "Implement BFS algorithm", link: "https://practice.geeksforgeeks.org/problems/bfs-traversal-of-graph/1", difficulty: "Easy", tags: ["graph", "bfs"] },
        { title: "Implement DFS algorithm", link: "https://www.geeksforgeeks.org/depth-first-search-or-dfs-for-a-graph/", difficulty: "Easy", tags: ["graph", "dfs"] },
        { title: "Detect Cycle in Directed Graph using BFS/DFS", link: "https://www.geeksforgeeks.org/detect-cycle-in-a-graph/", difficulty: "Medium", tags: ["graph", "dfs", "bfs"] },
        { title: "Detect Cycle in Undirected Graph using BFS/DFS", link: "https://practice.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1", difficulty: "Medium", tags: ["graph", "dfs", "bfs", "union-find"] },
        { title: "Search in a Maze (Rat in a Maze)", link: "https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1", difficulty: "Medium", tags: ["graph", "backtracking", "matrix"] },
        { title: "Minimum Step by Knight", link: "https://practice.geeksforgeeks.org/problems/steps-by-knight/0", difficulty: "Medium", tags: ["graph", "bfs"] },
        { title: "Flood Fill Algorithm", link: "https://leetcode.com/problems/flood-fill/", difficulty: "Easy", tags: ["graph", "dfs", "matrix"] },
        { title: "Clone a Graph", link: "https://leetcode.com/problems/clone-graph/", difficulty: "Medium", tags: ["graph", "dfs", "bfs", "hashmap"] },
        { title: "Making wired Connections", link: "https://leetcode.com/problems/number-of-operations-to-make-network-connected/", difficulty: "Medium", tags: ["graph", "union-find"] },
        { title: "Word Ladder", link: "https://leetcode.com/problems/word-ladder/", difficulty: "Hard", tags: ["graph", "bfs", "string"] },
        { title: "Dijkstra's Algorithm", link: "https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/", difficulty: "Medium", tags: ["graph", "greedy", "heap"] },
        { title: "Implement Topological Sort", link: "https://practice.geeksforgeeks.org/problems/topological-sort/1", difficulty: "Medium", tags: ["graph", "dfs", "bfs"] },
        { title: "Minimum time taken by each job (DAG)", link: "https://www.geeksforgeeks.org/minimum-time-taken-by-each-job-to-be-completed-given-by-a-directed-acyclic-graph/", difficulty: "Medium", tags: ["graph", "topological-sort", "dp"] },
        { title: "Find whether possible to finish all tasks from given dependencies", link: "https://www.geeksforgeeks.org/find-whether-it-is-possible-to-finish-all-tasks-or-not-from-given-dependencies/", difficulty: "Medium", tags: ["graph", "topological-sort"] },
        { title: "Find the number of Islands", link: "https://practice.geeksforgeeks.org/problems/find-the-number-of-islands/1", difficulty: "Medium", tags: ["graph", "dfs", "bfs", "matrix", "union-find"] },
        { title: "Given a sorted Dictionary of an Alien Language, find order of characters", link: "https://practice.geeksforgeeks.org/problems/alien-dictionary/1", difficulty: "Hard", tags: ["graph", "topological-sort"] },
        { title: "Implement Kruskal's Algorithm", link: "https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/", difficulty: "Medium", tags: ["graph", "mst", "union-find", "greedy"] },
        { title: "Implement Prim's Algorithm", link: "https://www.geeksforgeeks.org/prims-minimum-spanning-tree-mst-greedy-algo-5/", difficulty: "Medium", tags: ["graph", "mst", "greedy", "heap"] },
        { title: "Total number of Spanning Trees in a graph", link: "https://www.geeksforgeeks.org/total-number-spanning-trees-graph/", difficulty: "Hard", tags: ["graph", "mst", "math"] },
        { title: "Implement Bellman Ford Algorithm", link: "https://practice.geeksforgeeks.org/problems/negative-weight-cycle/0", difficulty: "Medium", tags: ["graph", "shortest-path"] },
        { title: "Implement Floyd Warshall Algorithm", link: "https://practice.geeksforgeeks.org/problems/implementing-floyd-warshall/0", difficulty: "Medium", tags: ["graph", "dp", "shortest-path"] },
        { title: "Travelling Salesman Problem", link: "https://www.geeksforgeeks.org/travelling-salesman-problem-set-1/", difficulty: "Hard", tags: ["graph", "dp", "backtracking"] },
        { title: "Graph Coloring Problem", link: "https://www.geeksforgeeks.org/graph-coloring-applications/", difficulty: "Hard", tags: ["graph", "backtracking"] },
        { title: "Snake and Ladders Problem", link: "https://leetcode.com/problems/snakes-and-ladders/", difficulty: "Medium", tags: ["graph", "bfs", "matrix"] },
        { title: "Find bridge in a graph", link: "https://www.geeksforgeeks.org/bridge-in-a-graph/", difficulty: "Hard", tags: ["graph", "dfs"] },
        { title: "Count Strongly Connected Components (Kosaraju's Algo)", link: "https://practice.geeksforgeeks.org/problems/strongly-connected-components-kosarajus-algo/1", difficulty: "Hard", tags: ["graph", "dfs", "scc"] },
        { title: "Check whether a graph is Bipartite or Not", link: "https://www.geeksforgeeks.org/bipartite-graph/", difficulty: "Medium", tags: ["graph", "bfs", "coloring"] },
        { title: "Detect Negative cycle in a graph", link: "https://www.geeksforgeeks.org/detect-negative-cycle-graph-bellman-ford/", difficulty: "Medium", tags: ["graph", "bellman-ford"] },
        { title: "Longest path in a Directed Acyclic Graph", link: "https://www.geeksforgeeks.org/find-longest-path-directed-acyclic-graph/", difficulty: "Medium", tags: ["graph", "topological-sort", "dp"] },
        { title: "Journey to the Moon", link: "https://www.hackerrank.com/challenges/journey-to-the-moon/problem", difficulty: "Medium", tags: ["graph", "union-find"] },
        { title: "Cheapest Flights Within K Stops", link: "https://leetcode.com/problems/cheapest-flights-within-k-stops/", difficulty: "Medium", tags: ["graph", "dp", "bfs", "bellman-ford"] },
        { title: "Oliver and the Game (HackerEarth)", link: "https://www.hackerearth.com/practice/algorithms/graphs/topological-sort/practice-problems/algorithm/oliver-and-the-game-3/", difficulty: "Medium", tags: ["graph", "topological-sort"] },
        { title: "Water Jug problem using BFS", link: "https://www.geeksforgeeks.org/water-jug-problem-using-bfs/", difficulty: "Medium", tags: ["graph", "bfs"] },
        { title: "Find if there is a path of more than k length from a source", link: "https://www.geeksforgeeks.org/find-if-there-is-a-path-of-more-than-k-length-from-a-source/", difficulty: "Medium", tags: ["graph", "backtracking"] },
        { title: "M-Coloring Problem", link: "https://practice.geeksforgeeks.org/problems/m-coloring-problem/0", difficulty: "Medium", tags: ["graph", "backtracking"] },
        { title: "Minimum edges to reverse to make path from source to destination", link: "https://www.geeksforgeeks.org/minimum-edges-reverse-make-path-source-destination/", difficulty: "Medium", tags: ["graph", "bfs", "0-1-bfs"] },
        { title: "Paths to travel each node using each edge (Seven Bridges)", link: "https://www.geeksforgeeks.org/paths-travel-nodes-using-edge-seven-bridges-konigsberg/", difficulty: "Hard", tags: ["graph", "euler-path"] },
        { title: "Vertex Cover Problem", link: "https://www.geeksforgeeks.org/vertex-cover-problem-set-1-introduction-approximate-algorithm-2/", difficulty: "Hard", tags: ["graph", "greedy", "approximation"] },
        { title: "Chinese Postman or Route Inspection", link: "https://www.geeksforgeeks.org/chinese-postman-route-inspection-set-1-introduction/", difficulty: "Hard", tags: ["graph", "euler-circuit"] },
        { title: "Number of Triangles in a Directed and Undirected Graph", link: "https://www.geeksforgeeks.org/number-of-triangles-in-directed-and-undirected-graphs/", difficulty: "Medium", tags: ["graph", "matrix", "math"] },
        { title: "Minimise the cashflow among a given set of friends", link: "https://www.geeksforgeeks.org/minimize-cash-flow-among-given-set-friends-borrowed-money/", difficulty: "Hard", tags: ["graph", "greedy"] },
        { title: "Two Clique Problem", link: "https://www.geeksforgeeks.org/two-clique-problem-check-graph-can-divided-two-cliques/", difficulty: "Hard", tags: ["graph", "bipartite"] }
      ]
    },
    {
      title: "Trie",
      problems: [
        { title: "Construct a Trie from scratch", link: "https://www.geeksforgeeks.org/trie-insert-and-search/", difficulty: "Medium", tags: ["trie", "string", "design"] },
        { title: "Find shortest unique prefix for every word in a given list", link: "https://www.geeksforgeeks.org/find-all-shortest-unique-prefixes-to-represent-each-word-in-a-given-list/", difficulty: "Medium", tags: ["trie", "string"] },
        { title: "Word Break Problem (Trie solution)", link: "https://www.geeksforgeeks.org/word-break-problem-trie-solution/", difficulty: "Hard", tags: ["trie", "dp", "string"] },
        { title: "Given a sequence of words, print all anagrams together", link: "https://practice.geeksforgeeks.org/problems/k-anagrams-1/0", difficulty: "Medium", tags: ["trie", "string", "hashmap"] },
        { title: "Implement a Phone Directory", link: "https://practice.geeksforgeeks.org/problems/phone-directory/0", difficulty: "Medium", tags: ["trie", "string"] },
        { title: "Print unique rows in a given boolean matrix", link: "https://practice.geeksforgeeks.org/problems/unique-rows-in-boolean-matrix/1", difficulty: "Medium", tags: ["trie", "matrix", "hashing"] },
        { title: "Maximum XOR of two numbers in an array", link: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/", difficulty: "Medium", tags: ["trie", "bit-manipulation"] },
        { title: "Count pairs with given XOR", link: "https://practice.geeksforgeeks.org/problems/count-pairs-with-given-xor/0", difficulty: "Easy", tags: ["trie", "bit-manipulation", "hashmap"] },
        { title: "Minimum XOR Value Pair", link: "https://practice.geeksforgeeks.org/problems/minimum-xor-value-pair/1", difficulty: "Easy", tags: ["trie", "bit-manipulation", "sorting"] },
        { title: "Find the maximum subarray XOR in a given array", link: "https://www.geeksforgeeks.org/find-the-maximum-subarray-xor-in-a-given-array/", difficulty: "Medium", tags: ["trie", "bit-manipulation"] }
      ]
    },
    {
      title: "Bit Manipulation",
      problems: [
        { title: "Count set bits in an integer", link: "https://practice.geeksforgeeks.org/problems/set-bits0143/1", difficulty: "Easy", tags: ["bit-manipulation"] },
        { title: "Find the two non-repeating elements in an array of repeating elements", link: "https://practice.geeksforgeeks.org/problems/finding-the-numbers0215/1", difficulty: "Medium", tags: ["bit-manipulation", "array"] },
        { title: "Count number of bits to be flipped to convert A to B", link: "https://practice.geeksforgeeks.org/problems/bit-difference/0", difficulty: "Easy", tags: ["bit-manipulation"] },
        { title: "Count total set bits in all numbers from 1 to n", link: "https://practice.geeksforgeeks.org/problems/count-total-set-bits/0", difficulty: "Medium", tags: ["bit-manipulation", "math"] },
        { title: "Find whether a number is power of two", link: "https://practice.geeksforgeeks.org/problems/power-of-2/0", difficulty: "Easy", tags: ["bit-manipulation", "math"] },
        { title: "Find position of the only set bit", link: "https://practice.geeksforgeeks.org/problems/find-position-of-set-bit3706/1", difficulty: "Easy", tags: ["bit-manipulation"] },
        { title: "Copy set bits in a range", link: "https://www.geeksforgeeks.org/copy-set-bits-in-a-range/", difficulty: "Easy", tags: ["bit-manipulation"] },
        { title: "Divide two integers without using multiplication, division and mod operator", link: "https://www.geeksforgeeks.org/divide-two-integers-without-using-multiplication-division-mod-operator/", difficulty: "Medium", tags: ["bit-manipulation", "math"] },
        { title: "Calculate square of a number without using *, / and pow()", link: "https://www.geeksforgeeks.org/calculate-square-of-a-number-without-using-and-pow/", difficulty: "Easy", tags: ["bit-manipulation", "math"] },
        { title: "Power Set (all subsets using bit manipulation)", link: "https://practice.geeksforgeeks.org/problems/power-set4302/1", difficulty: "Medium", tags: ["bit-manipulation", "recursion"] }
      ]
    }
  ]

};

const seedLoveBabbar = async () => {
  await connectDB();
  await DSASheet.findOneAndUpdate(
    { slug: loveBabbarData.slug },
    loveBabbarData,
    { upsert: true, new: true }
  );
  console.log('Love Babbar Sheet Seeded');
};

module.exports = seedLoveBabbar;